m=14
n=5
print(f"Adittioon of two no's {m} and {n} is:-")
print(m+n)
print(f"Subtraction of two no's {m} and {n} is:-")
print(m-n)
print(f"Multiplication of two no'sm{m} and {n} is:")
print(m*n)
print(f"Modulus of two no's {m} and {n} is:-")
print(m%n)
print(f"Division of two no's {m} and {n} is:-")
print(m/n)
print(f"Square of two no's {m} and {n} is:-")
print(f"{m**2} and {n**2}")
print("Square of two no's",m,"and",n,"is:-")
print("how are you")